mobile_detect.settings:
  type: config_object
  label: 'Mobile Detect'
  mapping:
    mobile_detect_is_mobile:
      type: boolean
      label: 'Add mobile_detect_is_mobile page cache context (experimental)'
