stages: [static_analysis, tests]

.static_analysis: &static_analysis
  stage: static_analysis
  image: php:7.2-alpine
  tags: [docker, ekino, france]

.tests: &tests
  stage: tests
  image: php:${PHP_VERSION}-alpine
  script:
    - apk add --update --upgrade git libpng-dev
    - docker-php-ext-configure gd
    - docker-php-ext-install gd
    - curl -sSL https://getcomposer.org/composer.phar -o /usr/local/bin/composer && chmod a+x /usr/local/bin/composer
    - composer global require hirak/prestissimo
    - composer install
    - ./vendor/bin/phpunit --testsuite=tests
  tags: [docker, ekino, france]

phpcs:
  <<: *static_analysis
  script:
    - apk add --update --upgrade git libpng-dev
    - docker-php-ext-configure gd
    - docker-php-ext-install gd
    - curl -sSL https://getcomposer.org/composer.phar -o /usr/local/bin/composer && chmod a+x /usr/local/bin/composer
    - composer global require hirak/prestissimo
    - composer install
    - ./vendor/bin/phpcs --standard=vendor/drupal/coder/coder_sniffer/Drupal --ignore=vendor/ ./
    - ./vendor/bin/phpcs --standard=vendor/drupal/coder/coder_sniffer/DrupalPractice --ignore=vendor/ --exclude=DrupalPractice.Commenting.ExpectedException ./

phpstan:
  <<: *static_analysis
  script:
    - apk add --update --upgrade git libpng-dev
    - docker-php-ext-configure gd
    - docker-php-ext-install gd
    - curl -sSL https://getcomposer.org/composer.phar -o /usr/local/bin/composer && chmod a+x /usr/local/bin/composer
    - composer global require hirak/prestissimo
    - composer install
    - composer require --dev phpstan/phpstan
    - ./vendor/bin/phpstan analyse --level=2 -c quality-analysis/phpstan/phpstan.neon src tests images_optimizer.module

php-5.6:
  <<: *tests
  variables:
    PHP_VERSION: "5.6"

php-7.0:
  <<: *tests
  variables:
    PHP_VERSION: "7.0"

php-7.1:
  <<: *tests
  variables:
    PHP_VERSION: "7.1"

php-7.2:
  <<: *tests
  variables:
    PHP_VERSION: "7.2"
