alqueriaUsers.settings:
  type: config_object
  label: 'Configuración para sección de usuarios alqueria'
alqueriaReceta.settings:
  type: config_object
  label: 'Configuración para formulario sube tu receta'