# Schema for the configuration files of the Images Optimizer module.

iamges_optimizer.optimizer.settings:
  type: config_object

images_optimizer.jpegoptim.settings:
  type: config_object
  mapping:
    binary_path:
      type: string
      label: 'Binary path'
    quality:
      type: integer
      label: 'Quality'
    timeout:
      type: integer
      label: 'Timeout'

images_optimizer.pngquant.settings:
  type: config_object
  mapping:
    binary_path:
      type: string
      label: 'Binary path'
    minimum_quality:
      type: integer
      label: 'Minimum quality'
    maximum_quality:
      type: integer
      label: 'Maximum quality'
    timeout:
      type: integer
      label: 'Timeout'
